name: WeaponsAPI
main: com.github.robotnikthingy.weaponsapi.WeaponsAPIPlugin
version: 1.0.0
description: Used to create and manage weapons of all types
authors: [Robotnikman, 2008Choco, ysl3000]
load: STARTUP